apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawler-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: crawler-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crawler-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: crawler-service-account
  namespace: default
roleRef:
  kind: Role
  name: crawler-role
  apiGroup: rbac.authorization.k8s.io