apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-worker
  labels:
    app: crawler
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crawler
      component: worker
  template:
    metadata:
      labels:
        app: crawler
        component: worker
    spec:
      containers:
      - name: worker
        image: crawler:latest
        imagePullPolicy: IfNotPresent
        command: ["crawler", "worker", "--concurrency", "2"]
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: RUST_LOG
          value: "info,crawler=debug"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MONGODB_URL
          value: "mongodb://mongodb-service:27017"
        - name: POSTGRES_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/crawler"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/crawler/config
        - name: chrome-data
          mountPath: /tmp/chrome-data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pgrep crawler || exit 1
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pgrep crawler || exit 1
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: crawler-config
      - name: chrome-data
        emptyDir: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crawler-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crawler-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60